# Generated by Django 5.1.2 on 2025-02-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task_student_side", "0001_initial"),
        ("task_tutor_side", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task_tutor_side.tasks"
            ),
        ),
    ]
