# Generated by Django 5.1.2 on 2025-02-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_in_session', '0001_initial'),
        ('task_student_side', '0002_initial'),
        ('task_tutor_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended', to='students_in_session.studentsinsession'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended', to='task_tutor_side.tasks'),
        ),
    ]
