apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: studyzed
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;']
      
      containers:
      - name: notification-service
        image: notification_management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:  
        - configMapRef:
            name: notification-service-config
        - secretRef:
            name: notification-service-secrets
        volumeMounts:
        - name: notification-service-code
          mountPath: /app
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: notification-service-storage
        # hostPath:
        #   path: "/home/mrlionbyte/Project/Study-Zed/BackendServices/Usermanagement_Service/Usermanagement"
        #   type: Directory
        persistentVolumeClaim:
          claimName: notification-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: studyzed
spec:
  selector:
    app: notification-service
  ports:
    - port: 8007
      targetPort: 8000
  type: ClusterIP