# Generated by Django 5.1.2 on 2025-03-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_tutor', '0005_session_session_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_tutor.session', to_field='session_code')),
            ],
        ),
    ]
