# Generated by Django 5.1.2 on 2024-12-09 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_email_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_temporary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='email_temporary',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email_temporary',
            name='no_of_try',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email_temporary',
            name='otp',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
