# Generated by Django 5.1.2 on 2024-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_email_temporary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_temporary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
