# Generated by Django 5.1.2 on 2024-12-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0005_email_temporary_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddon',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TUTOR', 'Tutor')], max_length=15),
        ),
    ]
