# Generated by Django 5.1.2 on 2024-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0008_alter_useraddon_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddon',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
