# Generated by Django 5.1.2 on 2024-12-15 09:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0009_remove_useraddon_phone_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cover_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
