# Generated by Django 5.1.2 on 2024-12-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0010_profile_cover_picture_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddon',
            name='google_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
