# Generated by Django 5.1.2 on 2025-01-09 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('currency', models.CharField(choices=[('USD', 'U.S. Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee')], default='INR', max_length=30)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('tickets', models.CharField(blank=True, choices=[('SOLVED', 'Solved'), ('RAISED', 'Raised')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], max_length=50)),
                ('currency', models.CharField(default='INR', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tranaction_date', models.DateField(auto_now_add=True)),
                ('wallet_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
