# Generated by Django 5.1.2 on 2025-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='currency',
            new_name='currency_mode',
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='tranaction_type',
            field=models.CharField(choices=[('CREDIT', 'Received + '), ('DEBIT', 'Withdrawn - ')], max_length=10),
        ),
    ]
