# Generated by Django 5.1.2 on 2025-01-09 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_currency_wallet_currency_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='wallet_transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
