# Generated by Django 5.1.2 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransactions_wallet_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='auto_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='auto_debit',
            field=models.BooleanField(default=False),
        ),
    ]
