# Generated by Django 5.1.2 on 2025-01-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_wallet_auto_credit_wallet_auto_debit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallettransactions",
            old_name="tranaction_date",
            new_name="transaction_date",
        ),
        migrations.RenameField(
            model_name="wallettransactions",
            old_name="tranaction_type",
            new_name="transaction_type",
        ),
    ]
