# Generated by Django 5.1.2 on 2025-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0005_rename_tranaction_date_wallettransactions_transaction_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user_code",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
