# celery-worker-notification (new)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-notification
  namespace: studyzed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-notification
  template:
    metadata:
      labels:
        app: celery-worker-notification
    spec:
      containers:
      - name: celery-worker-notification
        image: mrlionbyte/celery-worker-notification:v1.3.0
        command: ["celery", "-A", "Notification.celery", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-service:6379"
        - name: DJANGO_SETTINGS_MODULE
          value: "Notification.settings"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: SECRET_KEY
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
          requests:
            memory: "512Mi"
            cpu: "250m"