apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  namespace: studyzed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      dnsPolicy: "None"  # Disable internal DNS policy
      dnsConfig:
        nameservers:
          - 8.8.8.8  # Use Google's public DNS
          - 8.8.4.4  # Use Google's public DNS
      containers:
      - name: communication-service
        image: mrlionbyte/messages-management:v1.4.0
        
        ports:
          - containerPort: 8006
        envFrom:
          - secretRef:
              name: communication-service-secrets
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "Message_Video.settings"
        command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "Message_Video.asgi:application"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: studyzed
spec:
  selector:
    app: communication-service
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 8006
  type: ClusterIP