# Generated by Django 5.1.2 on 2025-01-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0011_useraddon_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddon',
            name='user_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
