# Generated by Django 5.1.2 on 2025-01-31 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_setter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceofsession',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
