# Generated by Django 5.1.2 on 2025-01-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("started_on", models.DateTimeField(auto_now_add=True)),
                ("completed_on", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_late_submission", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAssessmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_response", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(null=True)),
            ],
        ),
    ]
