# Generated by Django 5.1.2 on 2025-01-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment_student_side", "0001_initial"),
        ("assessment_tutor_side", "0001_initial"),
        ("students_in_session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassessment",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment",
                to="assessment_tutor_side.assessments",
            ),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="student_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="students_in_session.studentsinsession",
            ),
        ),
        migrations.AddField(
            model_name="studentassessmentresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment_tutor_side.assessment_questions",
            ),
        ),
        migrations.AddField(
            model_name="studentassessmentresponse",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="assessment_tutor_side.answer_options",
            ),
        ),
        migrations.AddField(
            model_name="studentassessmentresponse",
            name="student_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment_student_side.studentassessment",
            ),
        ),
    ]
