# Generated by Django 5.1.2 on 2025-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_student_side', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentresponse',
            name='mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
