apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-notification
  namespace: studyzed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-notification
  template:
    metadata:
      labels:
        app: celery-worker-notification
    spec:
      containers:
      - name: celery-worker-notification
        image: mrlionbyte/celery-worker-notification:v1.3.7
        command: ["celery", "-A", "Notification", "worker", "--loglevel=info", "--statedb=/celery-worker/state.db"]
        env:
        - name: REDIS
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: LOCATION
          value: "redis://redis-service:6379/1"
        - name: CELERY_BROKER_URL
          value: "redis://redis-service:6379"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis-service:6379"
        - name: DJANGO_SETTINGS_MODULE
          value: "Notification.settings"
        - name: FIREBASE_CREDENTIALS_PATH
          value: "/app/firebase/key.json"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: SECRET_KEY
        volumeMounts:
        - name: celery-worker-dir
          mountPath: /celery-worker
        - name: firebase-credentials-volume
          mountPath: /app/firebase
          readOnly: true

      volumes:
      - name: celery-worker-dir
        emptyDir: {}
      - name: firebase-credentials-volume
        secret:
          secretName: firebase-credentials
