apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: studyzed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: mrlionbyte/notification-management:v1.4.4.0
        ports:
          - containerPort: 8007
        envFrom:
          - secretRef:
              name: notification-service-secrets
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: DJANGO_SETTINGS_MODULE
          value: "Notification.settings"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: FIREBASE_CREDENTIALS_PATH
          value: "/app/firebase/key.json"
        volumeMounts:
          - name: firebase-secret
            mountPath: "/app/firebase"
            readOnly: true
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-credentials 

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: studyzed
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8007
    targetPort: 8007
  type: ClusterIP
