# Generated by Django 5.1.2 on 2025-01-09 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor_code', models.CharField(max_length=150)),
                ('session_code', models.CharField(max_length=150)),
                ('subscription_type', models.IntegerField(choices=[(1, 'one-month'), (3, 'three-months'), (6, 'six-months'), (12, 'twelve-months')])),
                ('purchased_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('expiry_time', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], max_length=20)),
                ('subscription_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_buy.subscription')),
            ],
        ),
    ]
