# Generated by Django 5.1.2 on 2025-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='purchased_on',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
