# Generated by Django 5.1.2 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_buy', '0002_remove_subscription_purchased_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
