# Generated by Django 5.1.2 on 2025-01-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_buy', '0003_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
