# Generated by Django 5.1.2 on 2025-01-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session_tutor", "0005_session_session_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment_Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=1250)),
                ("max_score", models.PositiveIntegerField()),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MLC", "Multiple Choice"), ("OPEN", "Open-Ended")],
                        default="OPEN",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer_Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_no", models.PositiveIntegerField()),
                ("option", models.TextField(max_length=1250)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "questions_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="assessment_tutor_side.assessment_questions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_title", models.CharField(max_length=250)),
                ("assessment_description", models.TextField(blank=True)),
                ("created_on", models.DateField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "session_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_tutor.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment_questions",
            name="assessment_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment_tutor_side.assessments",
            ),
        ),
    ]
