# Generated by Django 5.1.2 on 2025-03-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_tutor_side', '0002_assessments_total_mak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessments',
            old_name='total_mak',
            new_name='total_mark',
        ),
    ]
