apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: studyzed
spec:
  selector:
    app: notification-service
  ports:
    - port: 8007
      targetPort: 8000
      nodePort: 30007 
  type: NodePort
