# Generated by Django 5.1.2 on 2025-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_tutor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_code",
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_discription",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_duration",
            field=models.IntegerField(
                choices=[
                    (1, "one-month"),
                    (3, "three-months"),
                    (6, "six-months"),
                    (12, "twelve-months"),
                ]
            ),
        ),
    ]
