# Generated by Django 5.1.2 on 2025-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tutor', '0002_alter_session_session_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_duration',
            field=models.CharField(choices=[(1, 'one-month'), (3, 'three-months'), (6, 'six-months'), (12, 'twelve-months')]),
        ),
    ]
