# Generated by Django 5.1.2 on 2025-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_tutor', '0004_alter_session_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_grade',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
