# Zookeeper
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: studyzed
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.9
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_LOG4J_PROP
          value: "log4j.rootLogger=OFF, stdout"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: ["ReadWriteOnce"]

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: studyzed
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
  clusterIP: None
---

# Kafka
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: studyzed
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:  # ✅ Moved outside of 'containers' section
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /bitnami/kafka"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
      containers:
      - name: kafka
        image: bitnami/kafka:3.9
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka.studyzed.svc.cluster.local:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.rootLogger=OFF"
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: studyzed
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka
  clusterIP: None