apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
  namespace: studyzed
spec:
  serviceName: "payment-db"
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_DB
              value: "payment_studyzed"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: payment-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: payment-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: studyzed
spec:
  ports:
    - port: 5437
      targetPort: 5432
  selector:
    app: payment-db
  clusterIP: None