# Generated by Django 5.1.2 on 2025-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tutor_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
